export const cookingBooks = [
    "On Cooking",
    "The JOY OF COOKING",
    "101 Chocolate Recipes",
    "Boston Cooking-School cook book",
    "Get Cooking",
    "Good Cooks Cookbook",
    "Cooking Light Breads, Grains, & Pastas",
    "Cooking Light Complete Cookbook",
    "Fine Cooking Annual",
    "My Secret Recipe Book to Write in : Make Your Own Cookbook",
    "Fine Cooking Chocolate 150 Delicious And Decadent Recipes",
    "The Cooking Club Cookbook",
    "Wagashi and more",
    "Cooking light breads, grains & pastas",
    "Salads",
    "How to Cook a Turkey",
    "Classic Essential Bread & Buns (Hawthorn Mini Series)",
    "Pasta",
    "Cooking Light Way to Lose Weight",
    "Cooking Light: Tex-Mex",
    "Cooking Light Soup (Cooking Light)",
    "5 : 2-Diät-Kochbuch : Die besten Kurzzeitfasten Rezepte für ernährungsbewusste Menschen. Inklusive Einführung in die 5",
    "The Good Cooks Cookbook : Healthy Kitchen Low Carb Diet - It Just Tastes Better Volume 1",
    "Anti-Inflammatory Cuisine",
    "Carnet de Cuisine",
    "Homemade with Love - I Licked the Spoon and Kept Using It",
    "Best Ever Secrets From The Cooking Light Test Kitchens",
    "Cooking Light Microwave",
    "Diabetes Kochbuch",
    "Blank Cookbook Recipes & Notes",
    "Cooking Light 2006 Annual Recipes (Cooking Light Annual Recipes)",
    "Cooking Light Weeknight (Cook's Essential Recipe Collection)",
    "Cooking Light Fish & Shellfish Cookbook (Cooking Light)",
    "Cooking Light Annual Recipes 2007 (Cooking Light Annual Recipes)",
    "Cooking Light Salad (Cooking Light)",
    "Cooking Light Oops!: 209 Solutions for Everyday Kitchen Mistakes",
    "Cooking light annual recipes 1999",
    "Cooking Light Grilling (Cooking Light)",
    "Cuisine de la Friteuse Ninja Foodi",
    "Cooking Light Crave!: Stacked, stuffed, cheesy, crunchy & chocolaty comfort foods",
    "Quick & easy microwaving snacks and appetizers",
    "Quick & easy microwaving secrets",
    "Microwaving America's favorites.",
    "Quick & easy microwaving snacks & appetizers",
    "Potatoes!",
    "Quick and Easy Microwaving Chicken (Quick & Easy Microwaving Library)",
    "Quick and Easy Microwaving",
    "S'mores, Shakes & Chocolate Cakes",
    "Cook's Cook",
    "Holidays In Harmony",
    "Delicious desserts from light to luscious",
    "The Wellness lowfat cookbook",
    "More joy of microwaving",
    "Tempura and sukiyaki",
    "Chocolate quick fix",
    "Quick & easy microwaving ground beef",
    "The Joy of microwaving",
    "Delish cupcakes by color",
    "Chop suey a la carte",
    "The Delish Cooking School",
    "Low-fat & healthy one-pot meals",
    "Electric bread",
    "Easy Natural Cooking - No-Fuss Fish & Seafood Recipes",
    "Cooking light fish & shellfish",
    "Cooking Light Annual Recipes 2017: Every Recipe! a Year's Worth of Cooking Light Magazine",
    "Cooking Light 2000",
    "Quick and Easy Microwaving Vegetables",
    "Cooking Light Cookbook",
    "Cooking Christmas with Book(s)",
    "Cooking Up A Country Christmas with Book(s)",
    "The Best of Cooking Light 5, Special Edition 124 of the Year's Greatest Recipes for All Cooks, for All Occasions",
    "Joy of Microwaving",
    "Cooking New American",
    "How To Break An Egg",
    "Tempura and Sukiyaki Japanese Cookbook",
    "Typical Japanese Cooking",
    "More Cooking with Old Bay Great New Recipes Featuring Old Bay Seasoning",
    "EASY TO DO COOKING ITALIAN",
    "Shortcut Suppers",
    "Super Suppers and Desserts (Kids Cooking Club)",
    "Electric Bread for Kids",
    "MeatMen Cooking Channel",
    "MeatMen Cooking Channel : Zi Char at Home",
    "Fish Recipes for Power XL Air Fryer",
    "50 Slow-Cooker Recipes That Will Make You a Food Prep Believer",
    "Dizionario di enogastronomia in cinque lingue",
    "50 Easy Slow Cooker Meals",
    "Cooking light annual recipes 2002",
    "Cooking Light Fresh Food Fast Weeknight Meals",
    "Cooking Light Lazy Gourmet",
    "Cooking Light Way to Cook",
    "Cooking Light Cooking on the Fly",
    "Cooking Light Annual Recipes 2010\r\n            \r\n                Cooking Light Annual Recipes",
    "Low-fat, low-calorie quick & easy cookbook",
    "All Recipes 30 Minutes To Cook (All Recipes)",
    "Fresh Food Superfast",
    "Cooking Light the Essential Dinner Tonight Cookbook",
    "Cooking Light annual recipes 2012",
];